-- Tabla para proyectos (Investigaciones)
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    client_name TEXT
);

-- Tabla para la Pizarra (Blackboard architecture)
-- Gestiona el estado y paso de mensajes entre agentes
CREATE TABLE IF NOT EXISTS blackboard_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    project_id BIGINT REFERENCES projects(id),
    current_stage TEXT NOT NULL,  -- 'research_needed', 'strategy_ready', etc
    agent_assigned TEXT,          -- 'marcus', 'alice', etc
    status TEXT DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'error'
    memory_payload JSONB          -- Datos flexibles del contexto (objetivo, chat_id, resultados)
);

-- Habilitar RLS (Seguridad) es buena práctica, pero para este bot de backend
-- permitiremos acceso total si se tiene la SERVICE_KEY, o acceso pública para testear.
-- (Opcional: puedes deshabilitar RLS si tienes problemas de permisos con el cliente simple)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE blackboard_state ENABLE ROW LEVEL SECURITY;

-- Políticas permisivas para empezar (¡CUIDADO EN PRODUCCIÓN REAL!)
CREATE POLICY "Enable all access for anon/service" ON projects FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for anon/service" ON blackboard_state FOR ALL USING (true) WITH CHECK (true);
